### ISSUE TITLE
Raspberry Pi 4 with Ubuntu 64bit

### ISSUE THREAD

**Issue by attenzione** [dogweather/yahboom-raspi-cooling-fan#5]
Thanks for python library, however I got some issues on 64bit installation:
```
ImportError: No module named RPi
```
```
ImportError: No module named PIL
```
```
vcgencmd: command not found
```
```
VCHI initialization failed
```

Finally, all issues are resolved and I got everything working on Pi 4 with Ubuntu 64bit. All dependencies:
```
sudo apt install -y python3-smbus python3-pip python3-rpi.gpio i2c-tools libraspberrypi-bin
sudo pip3 install Adafruit-SSD1306 Pillow
```

Can you please update README and confirm that it's working on 64bit os

**Comment by dogweather** [comment]
Hey, that's great. Thanks @attenzione. I don't really have time to test it at the moment, but I'll add your solution to the README, and we'll see if it works for other people.
