### ISSUE TITLE
Add I2C hat address instructions

### ISSUE THREAD

**Issue by stevebriskin** [dogweather/yahboom-raspi-cooling-fan#6]
Firstly, thanks for making this hat actually usable with clear, concise instructions!

Scripts are hardcoded to find the hat at address 0x0d (also per Yahboom's docs), but mine was on address 0x3c. I don't know how common this is, but would be nice to have a debugging section on finding the address via 'i2cdetect -y 1' and updating scripts. I'm on a Pi 4B.

Edit: turned out to be faulty hat.

**Comment by dogweather** [comment]
I'm glad you figured it out.
