### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by bml5631** [dogweather/yahboom-raspi-cooling-fan#7]
Thanks for making this as it is way more usable than the original.

This is more of a request than issue.

Is there any way to adjust brightness?

Thanks for your help!!!

**Comment by dogweather** [comment]
Hi @bml5631 thank you! I don't have a 100% answer for you, but I have a pretty good guess. You can lower the brightness by setting lower RGB values. They work just like CSS. For example, you'll see `0xFF` (decimal 256) a lot in the code. This is full power for one of the three colors. Try instead hexadecimal `0x80` — which is one half (decimal 128) or `0x40` (decimal 64) - one quarter. Experiment. You should see a difference. This is why `0x00` is "off" - zero power. E.g.:

## Bright White

`0xFFFFFF`

## Dim White

`0x404040`


Now, there might be a brightness setting in the Yahboom that's completely separate from the LED colors, but I don't know about it. Good luck.

**Comment by bml5631** [comment]
Thanks so much for the response! I will give it a try and report back.
